/* ============================================================
   TRAIL MIX — media shelf  (THE ONLY FILE YOU EDIT TO ADD AUDIO / VIDEO)
   ------------------------------------------------------------
   The podcast, video and extras nodes are already built into the app.
   While a list is empty, Base Camp shows a tidy "coming soon" slot.

   Add an object to the right list. Every field except id/title is optional.

   PODCAST
     { id:"p1", title:"Countable or not? The pour test", url:"audio/p1.mp3",
       duration:"6:20", unit:6, module:"g6m1", transcript:"…" }
       - url can be a file in an audio/ folder, or any https link.
       - external:true turns it into a Listen button (Spotify, Apple…).

   VIDEO
     { id:"v1", title:"Going to, will or -ing?", youtube:"VIDEOID",
       duration:"3:10", unit:7, module:"g7m7" }
       - or iframe:"https://…" for a non-YouTube player.

   EXTRAS  (Blooket games, NotebookLM decks, worksheets)
     { id:"x1", title:"Unit 6 Blooket", url:"https://…", unit:6 }

   unit:6 or unit:7 shows the item on that unit's page and Base Camp.
   module:"g6m5" also puts a chip on that module's rule card.

   LESSON PODCASTS (NotebookLM Audio Overviews, Brief format)
     stage:"g6s1"   → plays on that stage of the grammar trail and on
                      every module page in the stage ("Listen first").
     pattern:"pour" → plays on that pattern card (Patterns tab).
     The sources NotebookLM used are in docs/podcasts/sources/,
     the list is docs/podcasts/episodes.json, audio is in audio/.
     Listening to 90% of an episode gives +10 XP once.
   ============================================================ */
window.MEDIA = {
  podcasts: [
    {"id": "G6-1", "title": "How to Count Uncountable Foods", "url": "audio/G6-1.mp3", "duration": "1:32", "unit": 6, "stage": "g6s1", "transcript": "<p>This is the brief on countable and uncountable food words. Got a big grammar test coming up? Well, don't worry, because before you open that textbook, let's make talking about food much easier.</p><p>First, the key rule. Just picture a bowl of grapes and a glass of water. A noun is just a grammar word for a thing. If you can count it, like one egg, it's countable. But here's your golden rule. If you pour it or scoop it, like water or rice, it's uncountable. Can you say one water? No way. So instead of saying the wrong sentence, I want a rice, keep it natural. I want some rice.</p><p>Second, if we can't count the water itself, how do we ask for more? We count the container. To count uncountable food, use containers or pieces. The container gets the plural S, but the food word never changes.</p><p>Watch out for this classic mistake. She ate three slices of breads. The right sentence is she ate three slices of bread.</p><p>Finally, watch out for tricky nouns. Are there words that are never countable in English, even if they are in Thai? Yes. Words like advice, money, news, and homework never take an A or an S. So don't say, I have a lot of homeworks. Just say, I have a lot of homework tonight.</p><p>Okay, quick challenge. Which group is the word honey in? Options. A, countable. B, uncountable. C, both. Or D, plural only. Have a think. The answer is B, uncountable. You pour it. So there is no a honey or honeys. You just say some honey or a jar of honey. Whether you're counting eggs or jars of honey, knowing these simple rules will definitely help you ace that test.</p>"},
    {"id": "G6-2", "title": "Grammar Rules for Talking About Food", "url": "audio/G6-2.mp3", "duration": "1:41", "unit": 6, "stage": "g6s2", "transcript": "<p>This is the brief on your Unit 6 Grammar for Fabulous Food. This quick preview will help you get ready for your school test, so you can talk about what's in your shopping bag perfectly. Starting with a single item brings us to our first rule.</p><p>First, a and an just mean one. Use an before a vowel sound, like a, e, i, o, u, and a before a consonant sound.</p><p>Watch out, English spelling plays tricks. It's all about the sound. Hour has a silent H, so it's an hour, like an egg or a banana. So don't say, can I have a apple, please? Say, can I have an apple, please? Now, what about a larger amount of food?</p><p>Second, use some for positive sentences when you have the food, like there is some milk. Use any for negative sentences, like we don't have any sugar or for general questions. But here's a tricky exception. When you offer food to a friend, use some. Don't ask, would you like any tea? Say, would you like some tea? Right, so how do we say where the food is?</p><p>Finally, to say something exists in a place, use there is for one thing or there are for plural things. Plural just means more than one. Never use have for a place because have needs an owner. Instead of saying, in my school have a big canteen, you say, there is a big canteen at my school.</p><p>Let's try it. I would like blank and a banana, please. Is it A, an oranges, B, a oranges, C, an orange, or D, a orange? Have a think. It's C, an orange. Orange starts with a vowel sound, so we use an. And no S means just one. Mastering these small words makes your English sound natural and perfectly polite.</p>"},
    {"id": "G6-3", "title": "Much, Many, and A Lot Of", "url": "audio/G6-3.mp3", "duration": "1:47", "unit": 6, "stage": "g6s3", "transcript": "<p>This is the brief on much, many, and a lot of. Today, we're going to learn how to talk about big and small amounts, and ask about prices, which will help you ace your school tests.</p><p>First, let's look at describing big amounts before asking about them. Think of a lot of as your best friend. It works for plural words, meaning more than one, and uncountable words, things you can't count, like liquids. Just don't forget the A. Use many for plurals and much for uncountables in negative sentences and questions, like, there's a lot of traffic in Bangkok, and we don't have much time. A classic mistake? Don't say, I have so much friends. Instead, say, I have a lot of friends. And don't say, there isn't many milk. Just say, there isn't much milk.</p><p>Second, now that you can describe amounts, let's ask questions. Use how many for plurals and how much for uncountables. But what if you're asking about money? Just ask, how much is it? Like, how much is the green curry? It's 60 baht. Also, for short answers without a noun at the end, drop the of.</p><p>Here's another mistake. Never say, how many milk do we need? Instead, say, how much milk do we need? If asked, are there any nuts? Don't say, yes, there are a lot of. Just say, yes, there are a lot.</p><p>Finally, let's test this right now. There isn't blank sugar in this lemonade. It's not very sweet. Options? A, a lot. B, much. C, many. D, lot of. Have a think? Okay, got it? The answer is much. That's because sugar is uncountable and it's a negative sentence. Mastering these rules makes talking about amounts so easy.</p>"},
    {"id": "G6-4", "title": "Giving Advice With Should and Shouldn't", "url": "audio/G6-4.mp3", "duration": "1:40", "unit": 6, "stage": "g6s4", "transcript": "<p>This is the brief on giving good advice with should and shouldn't. Today's friendly preview will get you, my 13-year-old Thai student, completely ready for your school test by showing you how to give great advice to your friends in English without making any silly grammar mistakes.</p><p>First up, the golden rule. Use should plus the base verb. A base verb is just a normal everyday verb with absolutely no changes. No to, no s, and no ing. You know, should works exactly like the word can. You would never say he cans, so you must never say he shoulds. Let's hear some classic mistakes.</p><p>First, the wrong sentence. We should to go home now. Then the right one, we should go home now. Another wrong sentence is you don't should drink so much cola, and the right one, you shouldn't drink so much cola.</p><p>Second, how do we give advice so we sound friendly and not bossy? Well, good advice perfectly fits the problem. If a friend says I'm always tired, your advice is about sleep. To sound softer and kinder, we use the phrase I think or I don't think. For example, I don't think you should play games all night. English speakers actually prefer saying I don't think you should over I think you shouldn't. Remember to give great advice, just use should or shouldn't followed by the simple base verb.</p><p>Let's try it. You look tired, Ploy. You should blank to bed early tonight. Options? A, going, B, to go, C, goes, D, go. The answer is D, go. After should, we always use the base verb should go. No to, no S, no ing.</p>"},
    {"id": "G6-5", "title": "Ordering Cafe Food and Writing Party Invitations", "url": "audio/G6-5.mp3", "duration": "1:22", "unit": 6, "stage": "g6s5", "transcript": "<p>This is the brief on ordering food and writing friendly invitations. Today, we're going to learn how to speak confidently in a cafe and write a great party email. Being polite makes everyone smile.</p><p>First, we learn how to order the food, and then we learn how to invite our friends.</p><p>First, ordering politely. Use I'd like, which is short for I would like, or could I have? Then add a base verb. A base verb is the simplest form of an action word, like have. Oh, and saying I want a burger without saying please is like eating a burger without the bun. It doesn't work. Treat please as your magic key.</p><p>Here's a classic mistake. Don't say, I like a milkshake. Instead, say, I'd like a milkshake please. For prices, don't ask, how many is that? You must say, how much is that?</p><p>Second, let's invite our friends. A good email must answer what, when, and where. It must also ask, would you like to come? To sound friendly, use contractions. These are short, squished words like I'm or don't.</p><p>Watch out for little mistakes. Don't write, would you like come to my party? Do write, would you like to come to my party? And don't say, let me to know. Just say, let me know. So, always use I'd like at the cafe and remember your what, when, and where for invitations. A waiter asks, are you blank to order? What is the missing word? Is it A, ready for? B, already? C, ready? Or D, finish? The answer is C, ready. Are you ready to order? Means, do you know what you want?</p>"},
    {"id": "P6-01", "title": "How to Count Food Words in English", "url": "audio/P6-01.mp3", "duration": "1:24", "unit": 6, "pattern": "pour", "transcript": "<p>This is the brief on counting food words. You're about to start your Unit 6 food lesson, and this one simple trick is going to help you pass exams and speak English perfectly.</p><p>First, let's look at the stuff rule. When you use grammar nouns, which are just naming words for things, ask yourself what the food feels like in your hand. If you pour it like water or soup, spread it like butter or jam, or scoop it with a spoon like yoghurt or sugar, it's just stuff with no clear edges. You cannot count stuff. Do not use a, an, or add an s at the end. Imagine holding a handful of soup. It just spills everywhere. That's why it's uncountable stuff.</p><p>Second, how do we count it? Well, if food comes in separate pieces you can hold in one hand, like an apple, an egg, or a biscuit, it's a thing. You can count things, like one apple or two eggs. To count stuff, you must count its container, so a glass of water, a jar of honey, or a pot of yoghurt.</p><p>Finally, watch out for this classic trap. You might say the wrong sentence, I want a water and two sugars. We hear this mistake all the time. But remember, you cannot count stuff. The right sentence is, I want some water and a spoonful of sugar.</p><p>Just remember, if you pour it, spread it, or scoop it, you cannot count it.</p><p>Now, quick challenge, picture your fridge. Name five things inside it and decide if they're pour, spread, scoop, or hold one. Go ahead, pause the podcast, and think. Okay, for example, milk is pour and an apple is hold one. Enjoy your lesson today. You're going to be brilliant.</p>"},
    {"id": "P6-02", "title": "How to Count Food in English", "url": "audio/P6-02.mp3", "duration": "1:52", "unit": 6, "pattern": "grains", "transcript": "<p>This is the brief on how we count food in English. Today's preview is especially for you, our 13-year-old Thai student, getting ready for your school test. It's going to help you learn a new vocabulary pattern, so you sound completely natural when you talk about food.</p><p>First, let's look at the two grammar words you need to know. Countable means things we can actually count with numbers. And uncountable is for a big mass or group that we cannot count. Now, you might be wondering, why do we say some rice, but some lentils when they're both tiny? Well, size doesn't decide this. Habit does. Very small things we eat with a spoon like rice, sugar, and salt are just treated as an uncountable mass.</p><p>Second, because of this habit, pasta and toast are also uncountable masses. Some vegetables are masses too, like spinach, broccoli, and garlic. If you want to count them, you absolutely must name a part. For example, a head of broccoli, a clove of garlic, or a slice of toast. But words like beans, lentils, nuts, grapes, and crisps are countable, so they keep their S. Here is a helpful little clue. If your vocabulary list shows an S, the word is countable.</p><p>Finally, let's look at those classic mistakes. Saying two rices is wrong. A bowl of rice is right. Saying three garlics is wrong. Three cloves of garlic is right. And saying two toasts is wrong. Two slices of toast is right.</p><p>Remember, English counts individual pieces like beans, but treats things like rice as one big uncountable mass.</p><p>Okay, try this quick challenge. Say these four words with the word some, and add an S only where it belongs. Rice, bean, spinach, nut. Take a second to think. The correct answers are some rice, some beans, some spinach, and some nuts. Good luck with your lesson today.</p>"},
    {"id": "P6-03", "title": "Countable Animals and Uncountable Food", "url": "audio/P6-03.mp3", "duration": "1:25", "unit": 6, "pattern": "animal", "transcript": "<p>This is the brief on English food vocabulary patterns. As a 13-year-old student prepping for your A2 test and M4 exams, learning the secret trick to food words gives you a massive advantage.</p><p>First, let's look at the golden rule. A countable noun is something you can count with numbers, like 1, 2, 3. An uncountable noun is an amount where we use some. Whole animals and big foods are countable. But when we cut them up to eat, they become uncountable, like some chicken or some pizza. So why does English do this? Well, it separates the animal running around in the garden from the actual food sitting on your plate.</p><p>Second, let's hear the difference. Compare, there is a chicken in the garden to, I had some chicken for lunch. Or, Leo caught three fish, remember fish doesn't change spelling for plurals, versus, we had fish for dinner. Wait, is all meat uncountable then? No way. Burgers and sausages are shaped into specific forms, so they're always countable. And wild animals from Unit 7, like tigers, are always countable too.</p><p>Finally, let's dodge the classic exam mistake. Listen to this wrong sentence. I ate a chicken for lunch. That sounds silly, like you ate an entire bird. The right sentence is, I ate some chicken.</p><p>Remember, whole things are countable with numbers, but the cut-up parts we eat are uncountable with some.</p><p>Try it. Make two sentences with fish. One about the animal, one about the food. Okay, got it? The answers are, Leo caught three fish, and we had fish for dinner. Keep practicing these patterns, and you'll do brilliantly on your exams.</p>"},
    {"id": "P6-04", "title": "How Food Chooses Its Container", "url": "audio/P6-04.mp3", "duration": "1:37", "unit": 6, "pattern": "containers", "transcript": "<p>This is the brief on how food chooses its container. This is a quick, friendly preview for Unit 6 of the Trail Mix app to help you easily remember new vocabulary for your M4 entrance exam. Have you ever wondered why we don't put soup in a paper bag? Well, because it would be a messy disaster.</p><p>First, let's learn the key rule. Underneath your word list, there's a pattern. A pattern is just a rule that repeats itself to make learning easier. Two questions pick the container. Question one, what is the food like? You know, is it liquid, sticky, dry, or cooked? Question two, what is it made of? Glass, card, metal, or paper?</p><p>Second, let's look at the examples. Think of it like a simple matching game where the food's shape decides its home. So liquid plus card makes a carton of orange juice. Sticky plus glass makes a jar of honey. Dry pieces plus paper makes a packet of biscuits.</p><p>Finally, the classic mistakes. You really want to avoid this one. You might say, I bought a packet of beans. But wait, beans are cooked and kept for months, so they don't go in paper. Instead, you'd say, I bought a tin of beans.</p><p>So remember, just look at what the food is like and what the container is made of and you will always find the right word.</p><p>Now, let's try it. Walk around to 7-Eleven in your head. Find one thing for a carton, one for a jar, and one for a packet. You could say, a carton of orange juice, a jar of jam, and a packet of crisps. Good luck on your school test. You're going to do brilliant.</p>"},
    {"id": "P6-05", "title": "When to Use Cups or Glasses", "url": "audio/P6-05.mp3", "duration": "1:25", "unit": 6, "pattern": "cupglass", "transcript": "<p>This is the brief on English drinks vocabulary. Before your Unit 6 fabulous food lesson and M4 exam, we'll learn a brilliant trick to remember the right drink words.</p><p>First, the shape of what we drink from tells us what goes inside. The rule is simple. Hot in a cup, cold in a glass. A cup has a handle, right? Think of it as a safety tool so you don't burn your fingers. So cups are for hot drinks, like a cup of tea. A glass has no handle, and it's used for cold drinks. Thai iced tea is cold, so it comes in a glass.</p><p>Second, what is a glass actually made of? Let's look at the stuff versus the thing. Teachers call materials we can't count, like hard clear glass, uncountable. But objects we can count, like a drinking glass, are countable. So you can have a glass of water in a glass made of glass. Jars are also made of the stuff.</p><p>Finally, let's avoid a classic exam mistake. Saying, mint drinks a cup of cold milkshake is wrong. It must be, mint drinks a glass of cold milkshake. Two more correct examples. Grandpa drinks a cup of hot tea, and two glasses of water, please. Also, this jar is made of glass.</p><p>So remember your key rule. Hot drinks go in a cup with a handle, and cold drinks go in a glass. Name three hot drinks and three cold drinks. Say, a cup of or a glass of for each one. For example, a cup of tea, a cup of coffee, a cup of hot milk, and a glass of water, a glass of lemonade, a glass of orange juice.</p>"}
  ],
  videos: [],
  extras: []
};
